pit_solutions_fhir_sdk:
    healthcare_api:
        project_id: '%env(HEALTHCARE_API_PROJECT_ID)%'
        cloud_region: '%env(HEALTHCARE_API_CLOUD_REGION)%'
        data_set_id: '%env(HEALTHCARE_API_DATASET_ID)%'
        fhir_store_id: '%env(HEALTHCARE_API_FHIR_STORE_ID)%'
        credentials_path: '%env(HEALTHCARE_API_CREDENTIALS_PATH)%'
        selected_version: '%env(HEALTHCARE_API_SELECTED_VERSION)%'